"""
Modular LLM Providers for download-curator (Gemini, OpenAI, Anthropic, Ollama).
Uses strict structured JSON output and falls back to rule-based classification if needed.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Dict, Optional

import httpx

from download_curator.ai.base import BaseAIProvider
from download_curator.ai.rule_based import RuleBasedProvider
from download_curator.config import CuratorConfig
from download_curator.core.models import ExtractedMetadata, ProposalResult
from download_curator.core.safety import sanitize_filename

logger = logging.getLogger("download_curator.ai")


SYSTEM_PROMPT = """You are an expert file organizer for a macOS download folder.
Your task is to analyze file metadata and excerpt to suggest a clean, standardized filename and category.

Standard naming conventions:
- Academic papers: Author[_Author]_Year_Short_Title.ext (e.g. Acemoglu_Smith_2026_Credit_Markets.pdf)
- Books: Author_Year_Title.ext
- Slides: Topic_or_Title.ext
- Invoices/receipts: Merchant_YYYY-MM-DD_Description.ext
- Financial statements: Institution_YYYY-MM_Statement.ext
- Datasets: Dataset_Name_Version_Date.ext
- Installers: Application_Version_Architecture.ext
- Images: Meaningful_Description_or_Date.ext
- For unclear files: Category "Unclassified"

Available categories and destinations:
- Academic Papers -> "Academic Papers"
- Books -> "Books"
- Slides -> "Presentations"
- Invoices & Receipts -> "Financial/Invoices"
- Financial Statements -> "Financial/Statements"
- Datasets -> "Datasets"
- Installers -> "Installers"
- Images -> "Images"
- Archives -> "Archives"
- Code & Scripts -> "Code"
- Documents -> "Documents"
- Spreadsheets -> "Spreadsheets"
- Audio & Video -> "Media"
- Unclassified -> "Unclassified"

You MUST output ONLY a valid JSON object matching this schema:
{
  "suggested_filename": "string (including original file extension)",
  "category": "string (one of the available categories)",
  "destination": "string (relative destination directory)",
  "confidence": float (between 0.0 and 1.0),
  "reason": "string (concise one-line explanation)"
}
"""


def _build_user_prompt(file_path: Path, metadata: ExtractedMetadata) -> str:
    return (
        f"Original Filename: {file_path.name}\n"
        f"File Extension: {file_path.suffix}\n"
        f"Detected Type: {metadata.file_type}\n"
        f"Title: {metadata.title or 'N/A'}\n"
        f"Authors: {', '.join(metadata.authors) if metadata.authors else 'N/A'}\n"
        f"Year/Date: {metadata.date or metadata.year or 'N/A'}\n"
        f"Merchant/Institution: {metadata.merchant_or_institution or 'N/A'}\n"
        f"Application/Dataset Name: {metadata.application_name or metadata.dataset_name or 'N/A'}\n"
        f"Content Excerpt:\n{metadata.excerpt or 'N/A'}\n"
    )


class GeminiProvider(BaseAIProvider):
    def __init__(self, api_key: str, model: Optional[str] = None):
        self.api_key = api_key
        self.model = model or "gemini-2.5-flash"
        self.fallback = RuleBasedProvider()

    def generate_proposal(
        self,
        file_path: Path,
        metadata: ExtractedMetadata,
        config: CuratorConfig,
    ) -> ProposalResult:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent?key={self.api_key}"
        user_prompt = _build_user_prompt(file_path, metadata)

        payload = {
            "system_instruction": {"parts": [{"text": SYSTEM_PROMPT}]},
            "contents": [{"parts": [{"text": user_prompt}]}],
            "generationConfig": {
                "response_mime_type": "application/json",
                "temperature": config.ai.temperature,
            },
        }

        try:
            with httpx.Client(timeout=15.0) as client:
                res = client.post(url, json=payload)
                res.raise_for_status()
                data = res.json()
                text_content = data["candidates"][0]["content"]["parts"][0]["text"]
                parsed = json.loads(text_content)
                return ProposalResult(
                    suggested_filename=sanitize_filename(parsed["suggested_filename"]),
                    category=parsed["category"],
                    destination=parsed.get("destination", config.categories.get(parsed["category"], "Unclassified")),
                    confidence=float(parsed.get("confidence", 0.85)),
                    reason=str(parsed.get("reason", "Generated by Gemini")),
                )
        except Exception as e:
            logger.warning(f"Gemini API error: {e}. Falling back to rule-based.")
            return self.fallback.generate_proposal(file_path, metadata, config)


class OpenAIProvider(BaseAIProvider):
    def __init__(self, api_key: str, model: Optional[str] = None, base_url: Optional[str] = None):
        self.api_key = api_key
        self.model = model or "gpt-4o-mini"
        self.base_url = base_url or "https://api.openai.com/v1"
        self.fallback = RuleBasedProvider()

    def generate_proposal(
        self,
        file_path: Path,
        metadata: ExtractedMetadata,
        config: CuratorConfig,
    ) -> ProposalResult:
        url = f"{self.base_url.rstrip('/')}/chat/completions"
        user_prompt = _build_user_prompt(file_path, metadata)

        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            "response_format": {"type": "json_object"},
            "temperature": config.ai.temperature,
        }

        headers = {"Authorization": f"Bearer {self.api_key}"}

        try:
            with httpx.Client(timeout=15.0) as client:
                res = client.post(url, json=payload, headers=headers)
                res.raise_for_status()
                data = res.json()
                content = data["choices"][0]["message"]["content"]
                parsed = json.loads(content)
                return ProposalResult(
                    suggested_filename=sanitize_filename(parsed["suggested_filename"]),
                    category=parsed["category"],
                    destination=parsed.get("destination", config.categories.get(parsed["category"], "Unclassified")),
                    confidence=float(parsed.get("confidence", 0.85)),
                    reason=str(parsed.get("reason", "Generated by OpenAI")),
                )
        except Exception as e:
            logger.warning(f"OpenAI API error: {e}. Falling back to rule-based.")
            return self.fallback.generate_proposal(file_path, metadata, config)


class AnthropicProvider(BaseAIProvider):
    def __init__(self, api_key: str, model: Optional[str] = None):
        self.api_key = api_key
        self.model = model or "claude-3-5-haiku-20241022"
        self.fallback = RuleBasedProvider()

    def generate_proposal(
        self,
        file_path: Path,
        metadata: ExtractedMetadata,
        config: CuratorConfig,
    ) -> ProposalResult:
        url = "https://api.anthropic.com/v1/messages"
        user_prompt = _build_user_prompt(file_path, metadata)

        payload = {
            "model": self.model,
            "system": SYSTEM_PROMPT,
            "messages": [{"role": "user", "content": user_prompt}],
            "max_tokens": 512,
            "temperature": config.ai.temperature,
        }

        headers = {
            "x-api-key": self.api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        }

        try:
            with httpx.Client(timeout=15.0) as client:
                res = client.post(url, json=payload, headers=headers)
                res.raise_for_status()
                data = res.json()
                text_content = data["content"][0]["text"]
                # Extract JSON from potential markdown wrapping
                json_match = re.search(r"\{[\s\S]*\}", text_content)
                if json_match:
                    parsed = json.loads(json_match.group(0))
                    return ProposalResult(
                        suggested_filename=sanitize_filename(parsed["suggested_filename"]),
                        category=parsed["category"],
                        destination=parsed.get("destination", config.categories.get(parsed["category"], "Unclassified")),
                        confidence=float(parsed.get("confidence", 0.85)),
                        reason=str(parsed.get("reason", "Generated by Anthropic")),
                    )
                raise ValueError("No JSON object found in Anthropic response")
        except Exception as e:
            logger.warning(f"Anthropic API error: {e}. Falling back to rule-based.")
            return self.fallback.generate_proposal(file_path, metadata, config)


class OllamaProvider(BaseAIProvider):
    def __init__(self, model: Optional[str] = None, base_url: Optional[str] = None):
        self.model = model or "llama3.2"
        self.base_url = base_url or "http://localhost:11434"
        self.fallback = RuleBasedProvider()

    def generate_proposal(
        self,
        file_path: Path,
        metadata: ExtractedMetadata,
        config: CuratorConfig,
    ) -> ProposalResult:
        url = f"{self.base_url.rstrip('/')}/api/generate"
        user_prompt = _build_user_prompt(file_path, metadata)

        payload = {
            "model": self.model,
            "system": SYSTEM_PROMPT,
            "prompt": user_prompt,
            "format": "json",
            "stream": False,
            "options": {"temperature": config.ai.temperature},
        }

        try:
            with httpx.Client(timeout=30.0) as client:
                res = client.post(url, json=payload)
                res.raise_for_status()
                data = res.json()
                parsed = json.loads(data["response"])
                return ProposalResult(
                    suggested_filename=sanitize_filename(parsed["suggested_filename"]),
                    category=parsed["category"],
                    destination=parsed.get("destination", config.categories.get(parsed["category"], "Unclassified")),
                    confidence=float(parsed.get("confidence", 0.80)),
                    reason=str(parsed.get("reason", "Generated by Ollama")),
                )
        except Exception as e:
            logger.warning(f"Ollama error: {e}. Falling back to rule-based.")
            return self.fallback.generate_proposal(file_path, metadata, config)
